name: flask-redis-app
services:
  redis:
    image: redis:7.4.3-alpine
    volumes:
      - redis_data:/data
    networks:
      - app-net
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-net

volumes:
  redis_data:

networks:
  app-net:
    driver: bridge