services:
  postgresql:
    image: 'bitnami/postgresql:14.17.0-debian-12-r17'
    environment:
      POSTGRESQL_USERNAME: ${DB_POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${DB_POSTGRESQL_PASS}
      POSTGRESQL_DATABASE: postgresql
      POSTGRESQL_INITSCRIPTS_DIR: /docker-entrypoint-initdb.d
    volumes:
      - pg_data:/bitnami/postgresql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db-net
  pgadmin4:
    image: 'elestio/pgadmin:REL-9_3'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - db-net
# Definindo Volumes
volumes:
  pg_data:
# Definindo Redes
networks:
  db-net:
    driver: bridge